# Generated by Django 3.1.1 on 2021-01-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i1', models.TextField(null=True)),
                ('i2', models.TextField(null=True)),
                ('i3', models.TextField(null=True)),
                ('i4', models.TextField(null=True)),
                ('i5', models.TextField(null=True)),
                ('i6', models.TextField(null=True)),
                ('i7', models.TextField(null=True)),
                ('i8', models.TextField(null=True)),
                ('i9', models.TextField(null=True)),
                ('i10', models.TextField(null=True)),
                ('i11', models.TextField(null=True)),
                ('i12', models.TextField(null=True)),
                ('i13', models.TextField(null=True)),
                ('i14', models.TextField(null=True)),
                ('i15', models.TextField(null=True)),
                ('i16', models.TextField(null=True)),
                ('i17', models.TextField(null=True)),
                ('i18', models.TextField(null=True)),
            ],
        ),
    ]
